name: 'Chromatic Deployment'

on: push

jobs:
  chromatic-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      # Corepack 활성화 (Yarn Berry / pnpm 플러그인 관리)
      - name: Enable Corepack
        run: corepack enable

      # 의존성 설치 (immutable = lockfile 불일치 시 실패)
      - name: Install dependencies
        run: yarn install --immutable

      # Chromatic 배포
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
